language: node_js
node_js:
- node
before_script:
- npm install
script:
- node test.js
deploy:
  provider: heroku
  api_key:
    secure: BZ8r6MJICOCzOLBCoURUD8fiKJf9zCCK9a0Q6SfIvbAN4ULb0h5fTHMkWLid2lpgWPq9huKderJPrjvHGfp8Nrn5q/JqP7C1d5MHkzaGOQdb66tR5C+WVvV9/5ptm8gURZHfaSSnIBZVPuDU7651FEeBACinzrCn9RtQQ1VgnyXOlxabt5wAdi0EB0JKgiaDlxaIrSxI3trUjlD1Of9CGquudVks15VnDKfWN+/kVFrGfs8lB0UIRtEQX0jsOyGA3xQM2qP3S9abPHhCQUYppvgK2JP3Q64Fh2OMKNSQbhq/wC1JUFmfNIrEHTsYYA8elc/SmK8Tm0CmqLmLNDvav7xt9FGcho2BWAJWVG4IsAvmQNpG0azD+pbB6hwkhg7ULdbSsfv0Nl4+f/JTxq9qVP6/NQzUxpyU94byAwkzBPypOTXk+MlFdPuXMn/1tZWg9FWieDmcJ1itBI0/G/P5ypkjAmkfawzME/H/jNvaWeZ6Lc8S71Z3FOFppXRXl+QhEVfgngVlGMwI3PEAihQJu5yiZpma37QAJnH/RjZJOplcSwGkXvA4L40QoRPfCW0DpvhR57qojbNReTd2Rg4iOcZ6vhrk6E26Syoyl7ss9EsJzRZ86l+rkJOH9ql4aERRggyJI2SGQcdPhg+xheMiJzG1KQxrSz3RCNGWMOdPSs8=
